GET http://localhost:5000/api/workouts

###

GET http://localhost:5000/api/workouts/62e7519c3bbe9893f81880f2

###

POST http://localhost:5000/api/workouts
Content-type: application/json

{
    "title": "Dumbell Press",
    "load": 20,
    "reps": 10
}

###

DELETE http://localhost:5000/api/workouts/676798

###

PATCH http://localhost:5000/api/workouts/97877

